version: '3.7'

services:
  app:
    # build: .
    image: riderufa/flask_gg_e69
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379
    